import Head from "next/head";
import { initialFriends } from "../data/dummyData";
import { useState } from "react";

export default function Home() {
  const [friends, setFriends] = useState(initialFriends);
  const [isOpen, setIsOpen] = useState(false);

  const handleButtonClick = () => {
    setIsOpen((isOpen) => !isOpen);
  };

  const handleAddFriend = (friend: any) => {
    setFriends((friends) => [...friends, friend]);
    setIsOpen(false);
  };

  return (
    <>
      <Head>
        <title>Bill Splitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <div className="sidebar">
          <FriendsList friends={friends} />
          {isOpen && <FormAddFriend onAddFriend={handleAddFriend} />}
          <Button onClick={handleButtonClick}>
            {isOpen ? "Close" : "Add Friend"}
          </Button>
        </div>
        <FormSplitBill />
      </div>
    </>
  );
}

const FriendsList = ({ friends }: any) => {
  return (
    <ul>
      {friends.map((friend: any) => (
        <Friend friend={friend} key={friend.id} />
      ))}
    </ul>
  );
};

const Friend = ({ friend }: any) => {
  return (
    <li>
      <img src={friend.image} alt={friend.name} />
      <h3> {friend.name}</h3>
      {friend.balance < 0 && (
        <p className="red">
          You owe {friend.name} {Math.abs(friend.balance)}
        </p>
      )}
      {friend.balance > 0 && (
        <p className="green">
          {friend.name} owes you {Math.abs(friend.balance)}
        </p>
      )}
      {friend.balance === 0 && <p>You and {friend.name} are even</p>}
      <Button>Select</Button>
    </li>
  );
};

const Button = ({ children, onClick }: any) => {
  return (
    <button className="button" onClick={onClick}>
      {children}
    </button>
  );
};

const initialValues = {
  friendName: "",
  imgURL: "https://i.pravatar.cc/48?u=499476",
};

const FormAddFriend = ({ onAddFriend }: any) => {
  const [values, setValues] = useState<any>(initialValues);

  const handleAddFriend = (event: any) => {
    const { name, value }: any = event.target;
    setValues({ ...values, [name]: value });
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();

    if (!values.friendName || !values.imgURL) return;

    const id = crypto.randomUUID();

    const newFriend = {
      id,
      name: values.friendName,
      image: `${values.imgURL}?id={id}`,
      balance: 0,
    };
    onAddFriend(newFriend);

    setValues(initialValues);
  };

  return (
    <form className="form-add-friend" onSubmit={handleSubmit}>
      <label>🧍Friend name</label>
      <input
        type="text"
        name="friendName"
        value={values.friendName}
        onChange={handleAddFriend}
      />

      <label>🌅Image URL</label>
      <input
        type="text"
        name="imgURL"
        value={values.imgURL}
        onChange={handleAddFriend}
      />
      <Button>Add</Button>
    </form>
  );
};

const FormSplitBill = () => {
  return (
    <form className="form-split-bill">
      <h2>Split a bill with X</h2>
      <label>💰 Bill Value</label>
      <input type="text" />
      <label>🧍 Your expense</label>
      <input type="text" />
      <label>🧑‍🤝‍🧑 X&apos;s expense</label>
      <input type="text" disabled />
      <label>🤑 Who is paying the bill</label>
      <select>
        <option value="user">You</option>
        <option value="friend">X</option>
      </select>
      <Button>Split bill</Button>
    </form>
  );
};
